name: Build ARMv5

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: [ main ]
    paths: [ 'build.sh', 'Dockerfile', '.github/workflows/build.yml' ]
  workflow_dispatch:

jobs:

  build-armel:
    runs-on: ubuntu-24.04-arm
    outputs:
      RELEASE: ${{ steps.start_build.outputs.RELEASE }}
    strategy:
      matrix:
        arch: [armel]
    env:
        ARCH: ${{ matrix.arch }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - id: start_build
        run: |
          bash build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: armel
          path: ./*.tar.xz
          archive: false

  push:
    runs-on: ubuntu-latest
    needs: [build-armel]
    permissions:
      contents: read
      packages: write

    steps:
      
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: arfshl
          password: ${{ secrets.DOCKERPASS }}

      - name: Downcase Repo Name
        run: echo "REPONAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
         path: .
         merge-multiple: true

      - name: DEBUG; Check files
        run: ls -la

      - name: Push to GHCR and Docker Hub
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          platforms: |
            linux/arm/v5
          tags: |
            ghcr.io/${{ env.REPONAME }}:latest
            ghcr.io/${{ env.REPONAME }}:${{ needs.build-armel.outputs.RELEASE }}
            arfshl/devuan:latest
            arfshl/devuan:${{ needs.build-armel.outputs.RELEASE }}